name: Actualitzar Catàleg

on:
  schedule:
    # Executar cada dia a les 00:00
    - cron: '0 0 * * *'
  workflow_dispatch: # Permet executar manualment des de GitHub

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout del codi
      uses: actions/checkout@v3
      
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Instal·lar dependències
      run: npm install
      
    - name: Generar nou catàleg
      env:
        TMDB_READ_TOKEN: ${{ secrets.TMDB_READ_TOKEN }}
      run: node generate_catalog.js
      
    - name: Commit i Push si hi ha canvis
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add catalog.json
        # Comprovem si hi ha canvis abans de fer commit
        if git diff --staged --quiet; then
          echo "No hi ha canvis al catàleg."
        else
          git commit -m "Actualització automàtica del catàleg"
          git push
        fi
